name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configuration Environment
        shell: bash
        run: |
          echo 'android.sdk.channel=3' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          echo 'android.testoptions.manageddevices.emulator.gpu=swiftshader_indirect' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo '84831b9409646a918e30573bab4c9c91346d8abd' > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
          sed -i '' 's|return X509_CERT_DIR;|return "/system/etc/security/cacerts";|' boringssl/src/main/native/src/crypto/x509/x509_def.c
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: |
          ./gradlew :a:assemble
          ./gradlew :b:publishToMavenLocal
      - name: Test with Gradle
        run: |
          ./gradlew :a:allDevicesDebugAndroidTest
          rm -v app/build/outputs/androidTest-results/managedDevice/*/*/testlog/adb.additional_test_output*
      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs
          compression-level: 9
